### ISSUE TITLE
头像显示问题

### ISSUE THREAD

**Issue by winjeysong** [Sunshine168/Full-stack-Blog#1]
你好，头像的显示功能还没完成吗
😭

**Comment by Sunshine168** [comment]
已经修复了。。头像功能很早就实现  应该是上次修改的时候改错了
问题出现在写入头像路径的时候写入了本地文件的路径。
这个练手项目有很多问题，迟点会进一步完善。。  抱歉啦

**Comment by winjeysong** [comment]
感谢！
